language: rust
rust:
  - nightly
jobs:
  fast_finish: true
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE metalmon_test;'
before_script:
  - cargo install diesel_cli
  - diesel setup --database-url mysql://root@localhost/metalmon_test
