language: rust
rust:
  - nightly
jobs:
  fast_finish: true
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE metalmon_test;'
  - DATABASE_URL=mysql://root@localhost/metalmon_test > .env
before_script:
  - cargo install diesel_cli
  - diesel setup
